apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-nfs
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.nfs.csi.ceph.com # driver:namespace:operator
parameters:
  # (required) Name of the NFS-cluster as managed by Ceph.
  nfsCluster: my-nfs

  # (required) Hostname, ip-address or service that points to the Ceph managed
  # NFS-server that will be used for mounting the NFS-export.
  server: rook-ceph-nfs-my-nfs-a

  # clusterID is the namespace where the rook cluster is running
  # If you change this namespace, also change the namespace below where the secret namespaces are defined
  clusterID: rook-ceph # namespace:cluster

  # CephFS filesystem name into which the volume shall be created
  fsName: myfs

  # Ceph pool into which the volume shall be created
  # Required for provisionVolume: "true"
  pool: myfs-replicated

  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph # namespace:cluster

reclaimPolicy: Delete
allowVolumeExpansion: false
mountOptions:
  # uncomment the following line for debugging
  #- debug
